### ISSUE TITLE
Possible problem with IgnoringCyclicReferences

### ISSUE THREAD

**Issue by Lette** [dennisdoomen/FluentAssertions#192]
In version `2.0.1` the following test was passing:

```csharp
using FluentAssertions;
using NUnit.Framework;

namespace FluentAssertionTests
{
    [TestFixture]
    public class Tests
    {
        [Test]
        public void ShouldBeEquivalentTo_works()
        {
            var a = new Parent();
            a.Child1 = new Child(a, 1);
            a.Child2 = new Child(a);

            var b = new Parent();
            b.Child1 = new Child(b);
            b.Child2 = new Child(b);

            a.ShouldBeEquivalentTo(b, x => x
                .Excluding(y => y.Child1)
                .IgnoringCyclicReferences());
        }
    }

    public class Parent
    {
        public Child Child1 { get; set; }
        public Child Child2 { get; set; }
    }

    public class Child
    {
        public Child(Parent parent, int stuff = 0)
        {
            Parent = parent;
            Stuff = stuff;
        }

        public Parent Parent { get; set; }
        public int Stuff { get; set; }
        
    }
}
```

This test fails in `2.1.0`, and it doesn't pass in the latest nuget package (`3.2.1`) either.

It fails with `Expected property Child2.Parent.Child1.Stuff to be 0, but found 1.`, even though we explicitly stated that property `Child1` should be excluded and that we want to ignore cyclic references.

I'm fairly sure that the back reference `Child2.Parent` should be considered a cyclic reference.

Is there a cycle detection problem here, or am I using FA the wrong way?

**Comment by dennisdoomen** [comment]
Is this still an issue?

**Comment by Lette** [comment]
I would like to reassess, tomorrow.

**Comment by dennisdoomen** [comment]
Thanks. Let me know.

**Comment by Lette** [comment]
I ran `update-package` and got version `3.2.2`. The test above does not pass.

I have two questions:
* To me it seems like there was a breaking change between `2.0.1` and `2.1.0`. I couldn't find any mention of it in the release notes, but that may be me not understanding the problem completely. Do you know/remember why the behavior changed?
* If you look at the test, would you think that the test should pass? What do you think is the expected behavior?

Also, I now suspect that the problem I'm facing lies within the configuration. I base that assumption on the assertion message I get:

```text
Expected property Child2.Parent.Child1.Stuff to be 0, but found 1.

With configuration:
- Include only the declared properties
- Exclude property Child1
- Match property by name (or throw)
```

As you can see, there is no mention of me calling `IgnoringCyclicReferences()`.

**Comment by Lette** [comment]
I forked and rebuilt the latest om my machine, but no luck. Same behavior as before.

@vossad01 I'm sorry for not getting back to you earlier. Thanks for your input and the advice. In fact, we are already doing what you suggest. It doesn't seem to have any impact on the problem at hand, however.

**Comment by dennisdoomen** [comment]
So in short, I think your unit test initially succeeded because of a false positive. I've enhanced the logging of the configuration to better clarify the actual equivalency configuration that was used. But IMHO, the behavior you're seeing is indeed correct.

**Comment by vossad01** [comment]
@Lette I believe type-based configuration will not work in the example you provided because that configuration does not affect the root/subject object of the assertion (the first argument to the extension method, `a` in this case).

That exclusion is behavior I spotted a while ago that I think should be changed, but I either need to come up with an entirely new API that does not have that exclusion or it needs to wait to 4.0 because would be a breaking change.

If that would be a valid solution for you it would help by having identified a case "in the wild" where the current exclusion is an issue.  If that would be a solution, we could also provide guidance on how to use FA's extension points to work around the issue with type-based configuration, but those are relatively heavy-weight solutions for this problem.

Regarding the actual `IgnoringCyclicReferences` question, I do not know how it was implemented in 2.0.1.  However given the current implementation, I do expect this case to fail.  If you are looking for that behavior to change, what would be helpful is a proposal on how cyclic-reference detection should be implemented such that your case would pass.

**Comment by Lette** [comment]
I can't blame you for closing this issue. I just want to leave you with my thoughts:

The test above fails, since FA decides that the two graphs are not equivalent. If I wrap each of the root objects `a` and `b`  (of type `Parent`) in a new type `GrandParent` and check equivalence of those two graphs (where the root object now is of type `GrandParent`), the test does not fail. FA now concludes that the two graphs in fact are equivalent.

This is counter-intuitive, and IMHO wrong. If two graphs are equivalent, then any two sub-graphs of those graphs also must be equivalent. FA thinks otherwise.

I believe that the main culprit here is that FA does not consider the root object when looking for cyclic references. Whether that is something you would consider changing or not is totally up to you, of course. I respect the time and effort you have invested in this tool, and I realize that there might be forces that push you towards the current implementation.

Thank you for all your hard work.

**Comment by dennisdoomen** [comment]
Let me think a
