### ISSUE TITLE
ShouldAllBeEquivalentTo with Including still compares all properties

### ISSUE THREAD

**Issue by MichaelLogutov** [dennisdoomen/fluentassertions#245]
The recent version broken a lot of our tests due to the fact that ShouldAllBeEquivalentTo with Including still compares all properties and not only that specified in equivalency options:

    public class MyClass
    {
        public string A { get; set; }
        public string B { get; set; }
    }

    [TestMethod]
    public void Test ()
    {
        // arrange
        var result = new[] { new MyClass { A = "aaa", B = "bbb" } };

        // assert
        var expected = new MyClass
                        {
                            A = "aaa",
                            B = "ccc"
                        };

        result.ShouldAllBeEquivalentTo (new[] { expected },
                                        options => options.Including (x => x.A));
    }

Got:
```
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Expected item[0].B to be "ccc", but "bbb" differs near "bbb" (index 0).

With configuration:
- Use declared types and members
- Compare enums by value
- Select member Bug.Tests+MyClass.A
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- FluentAssertions.Equivalency.ShouldAllBeEquivalentToHelper+CollectionMemberOrderingRuleDecorator
```

**Comment by dennisdoomen** [comment]
Thanks for reporting that. I'll try to look at that tonight. Sounds like a pretty serious bug. We must be missing a unit test if that is true.

**Comment by dennisdoomen** [comment]
Might be caused by the same reasons that caused #194.

**Comment by dennisdoomen** [comment]
Yes, we're missing a couple of unit tests...

**Comment by dennisdoomen** [comment]
@vossad01 Do you remember the purpose of [this construction](https://github.com/dennisdoomen/fluentassertions/blame/develop/FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsBase.cs#L552)?

**Comment by vossad01** [comment]
I would need to dig into the code to give a more precise answer, which I can to tonight if you need.

The just of it was because of ordering of the rules.  Previously, the rules were added immediately which required some methods to clear the collection or rules or remove specific ones.  As I introduced more ways to interact with those rules, the clearing logic seemed a little odd and wanted to impose a invocation order dependency on the methods.

The boolean is used to defer inserting of the standard rules until all other configuration is completed so the configuration did not need to concern itself with preserving them.  Strangely, in searching that file it appears the boolean is no longer used?

**Comment by dennisdoomen** [comment]
It is used, but I suspect you're changes and my introduction of a global options class is not working together. The boolean is now evaluated multiple times.

**Comment by dennisdoomen** [comment]
Pfew, that was a tricky one.
