### ISSUE TITLE
ShouldBeEquivalentTo between an Enum and Int

### ISSUE THREAD

**Issue by nikrollz** [dennisdoomen/fluentassertions#247]
I feel like this should work, but it doesn't...

       public enum testEnum
        }
            First = 1
        }

        public class Object1
        {
            public int IntOrEnum;
        }
        public class Object2
        {
            public testEnum IntOrEnum;
        }
        public void QuickTest()
        {
            Object1 obj1 = new Object1();
            Object2 obj2 = new Object2();

            obj1.IntOrEnum = 1;
            obj2.IntOrEnum = testEnum.First;

            obj1.ShouldBeEquivalentTo(obj2, options => options.ComparingEnumsByValue());
        }

The error looks like this:
 Expected member IntOrEnum to be First, but found 1.

**Comment by dennisdoomen** [comment]
So the problem is actually kind of by-design. While traversing the object graph, it really traverses the subject's object graph rather than the expectation. As such, when FA reaches the `obj1.IntOrEnum` it concludes it's dealing with a simple type and completely bypasses the enumeration check. Have to figure out how to solve this.
