### ISSUE TITLE
ShouldBeEquivalentTo does not detect difference in multi-dimensional array

### ISSUE THREAD

**Issue by slogen** [dennisdoomen/fluentassertions#260]
The test cases below show that ShouldBeEqualTo does not detect differences in multi-dimensional arrays.

```C#
    public class FluentAssertionArrayTest
    {
        [Test]
        public void When_applying_ShouldBeEquivalentTo_to_equal_multi_dimensional_array_it_should_not_throw()
        {
            var x = new[,] { { 1, 2, 3 }, { 4, 5, 6 } };
            var y = new[,] { { 1, 2, 3 }, { 4, 5, 6 } };
            Action act = () => x.ShouldBeEquivalentTo(y);
            act.ShouldNotThrow();
        }
        [Test]
        public void When_applying_ShouldBeEquivalentTo_to_a_multi_dimensional_array_with_diff_it_should_throw()
        {
            var x = new[,] {{1, 2, 3}, {4, 5, 6}};
            var y = new[,] { { 1, 2, 3 }, { 4, -5, 6 } };
            Action act = () => x.ShouldBeEquivalentTo(y);
            act.ShouldThrow<Exception>();
            // Fails: "Expected a <System.Exception> to be thrown, but no exception was thrown."
        }
        [Test]
        public void When_applying_ShouldBeEquivalentTo_to_a_single_dimensional_array_with_diff_it_should_throw()
        {
            var x = new[] {4, 5, 6};
            var y = new[] { 4, -5, 6 };
            Action act = () => x.ShouldBeEquivalentTo(y);
            act.ShouldThrow<Exception>();
        }
        [Test]
        public void When_applying_ShouldAllBeEquivalentTo_to_a_single_dimensional_array_with_diff_it_should_throw()
        {
            var x = new[] { 4, 5, 6 };
            var y = new[] { 4, -5, 6 };
            Action act = () => x.ShouldAllBeEquivalentTo(y);
            act.ShouldThrow<Exception>();
        }
    }
```

**Comment by vossad01** [comment]
For now, you can work around this issue by directing FA to use the run-time types.

```c#
[Test]
When_applying_ShouldBeEquivalentTo_to_a_multi_dimensional_array_with_diff_it_should_throw()
{
    var x = new[,] {{1, 2, 3}, {4, 5, 6}};
    var y = new[,] { { 1, 2, 3 }, { 4, -5, 6 } };
    Action act = () => x.ShouldBeEquivalentTo(y, o => o.RespectingRuntimeTypes());
    act.ShouldThrow<Exception>();
}
```

I will have to take a look at this.  Multi-dimensional arrays apparently do not implement the generic `IEnumerable` interfaces so FA is loosing the type and it ends up seeing the `int`s as `object`s.  Since `object` has no members, any two equivalent under structural comparison.

**Comment by dennisdoomen** [comment]
Was trying to analyze this and started to wonder how this should be handled. By default, `ShouldBeEquivalentTo` will ignore the order of items in collections and arrays. But in the case of a jagged or multi-dimensional array I tend to think that the order is important. Let's see if we can get some opinions from [Gitter](https://gitter.im/dennisdoomen/fluentassertions).

**Comment by vossad01** [comment]
Posting here because I am concerned the impact Gitter will have when a future reader wants to understand what happened with respect to an issue.

Are there issues with current handling of jagged arrays?  I started down an implementation where I made multidimensional arrays behave like jagged arrays that happened to have be consistent in length.  However, I drew the conclusion that that was making too many assumptions about what the multidimensional array represented (how do we know "rows" are the appropriate grouping for that data set?) and that they arrays should be treated differently than jagged arrays.  In this case I thought the reasonable behavior was to preserve the order.

Pseudo Algorithm:
 1. Assert same rank
 2. Assert lengths of each rank are the same
 3. Assert the items, in order of iteration, are equivalent

While this is probably not the desired behavior of every user for every data set, I don't think we can reasonably handle all the ways an n-dimensional data structure might be used.  My thoughts were that the above would be simple, consistent, and defensible, if more specialized behavior was needed extension points could be used to override the behavior.

**Comment by dennisdoomen** [comment]
So it seems we can't use any of the existing equivalency steps and need to introduce a new one.

**Comment by dennisdoomen** [comment]
Now...how do we iterate over an array of undefined dimensions.......

**Comment by vossad01** [comment]
The same way we do already actually.  Multidimensional arrays implement `IEnumerable` so the only complexity so needing to retrieve the type of objects in the array (`GetElementType()`) and create an `IEnumerable<T>` (`Enumerable.Cast<T>) with that type.

This should end up a lot like `GenericEnumerableEquivalencyStep` once you express the appropriately typed enumerables, the existing `EnumerableEquivalencyValidator` should work with the only difference being the need to specify the ordering rule.

**Comment by vossad01** [comment]
Since you self-assigned, I figure I should abandon my implementation.  If you have not gotten this far already, you might find the following helpful:

```
private static int[] GetLengths(Array subject)
{
	var ret = new int[subject.Rank];

	foreach (var dimension in Enumerable.Range(0, subject.Rank))
	{
		ret[dimension] = subject.GetLength(dimension);
	}

	return ret;
}
```

I already mentioned `Type.GetElementType` which was the other thing I had to figure out.

**Comment by dennisdoomen** [comment]
Sorry @vossad01, didn't know you were working on this. 

Just using `IEnumerable` won't be enough. We need to provide the exact indexes as part of the failure message. I'm introducing a new dedicated `IEquivalencyStep` just for this purpose.
