### ISSUE TITLE
Print x.0 when x is is a double/float representing a whole number

### ISSUE THREAD

**Issue by dennisdoomen** [dennisdoomen/FluentAssertions#4]
See original CodePlex [issue](https://fluentassertions.codeplex.com/workitem/12493)

**Comment by vossad01** [comment]
I think NUnit might provides some good conventions worth following.  If I recall correctly, it will print '1.0f' and other such suffixes on types to disambiguate beyond the integer vs floating point ambiguity raised here.

**Comment by somewhatabstract** [comment]
Like to original issue is broken. Can some more details be added to this?

**Comment by vossad01** [comment]
When there is a numeric *type* mismatch but the numeric *value* is the same the error message is akin to:

 > 4 does not equal 4

which does not allow the user to easily tell what the issue is.  Even when the user is aware of this limitation in FluentAssertions, it still can be challenging to find the culprit because there may be many members compared on an object in a single assertion.

Errors such as:

 > 4 does not equal 4.0

and

 > 4.0f does not equal 4.0d

could contribute significantly to quickly identifying the cause of a failing test.

**Comment by somewhatabstract** [comment]
Ah, yes. I see. Interesting. Thanks for adding the detail.
