### ISSUE TITLE
How to include additional object information after "because" phrase?

### ISSUE THREAD

**Issue by nohwnd** [dennisdoomen/FluentAssertions#523]
I am testing ASP.NET WebApi and I am writing test that validates PUT behavior: 
```csharp
var response = await HttpClient.PutAsJsonAsync($"/api/orders/{order.Id}", updatedOrder);
response.StatusCode.Should()
    .Be(HttpStatusCode.NoContent, 
    "because putting the order correctly should return no content");
```
If my test fails I get assertion message such as this: 
```
Expected object to be NoContent, because putting the order correctly 
should return no content, but found BadRequest.
``` 
This is fine, but my response contains the failure reason in its Content. Is there a way to tell the assertion to extract that information?
Something like:
```csharp
var response = await HttpClient.PutAsJsonAsync($"/api/orders/{order.Id}", updatedOrder);
response.StatusCode.Should()
    .Be(HttpStatusCode.NoContent, 
    "because putting the order correctly should return no content", ???, response.Content);
```
which would generate this failure message: 
```
Expected object to be NoContent, because putting the order correctly 
should return no content, but found BadRequest with "Id is not set. CustomerId is not set."
``` 
---
I know I can provide additional information to become part of the because phrase, but I cannot come up with wording that works for me, and personally I think such this information should not be part of the because clause.

I looked through the framework and did not find the option. I also looked at the implementation of `Be` and found out that with the current syntax it would be difficult to extend because of the `params` paramaeter. I can write my own extension method that has this functionality, but I would love to know if there is an official way, or if you'd consider adding it. If you would, then I will happily discuss the best way to implement it and provide a PR.

**Comment by vossad01** [comment]
Assuming nothing radical has changed with this library since I have last been in the code base, I think the appropriate implementation would be a new extension method enabling the following syntax:

```
var response = await HttpClient.PutAsJsonAsync($"/api/orders/{order.Id}", updatedOrder);
response.Should().HaveStatusCode(
     HttpStatusCode.NoContent, 
    "because putting the order correctly should return no content");
```

`HaveStatusCode` then has access to the `response` object and can generate an appropriate and detailed message.

The downside is I believe you are working with types outside the .NET Standard Library.  The implication is your the extension method could not be folded into FluentAssertions because of the dependency issue.  I think a new project `FluentAssertions.{Web/HttpClient/AspNet/WebApi/???}` would be welcomed by web developers but that is a little bigger undertaking for your extension method due to the publishing aspect.  I almost started that undertaking when I was shifted to web development a while back, but then life took me elsewhere.

[FluentAssertions.MVC](https://github.com/kevinkuszyk/FluentAssertions.MVC) is the closest thing I see in current existence, but you might look around yourself.

**Comment by vossad01** [comment]
However, I see now [`FluentAssertions.Json`](https://www.nuget.org/packages/FluentAssertions.Json/) is built out of this repository.  Thus, there is precedent for official FluentAssertion extensions and you might not automatically have to look at a separate [Community Extension](www.fluentassertions.com/#community-extensions), but you would have to work that with @dennisdoomen what is appropriate in this case.

**Comment by dennisdoomen** [comment]
In retrospect, I regret the decision to merge the two projects into a single repo. Not because that JSON support is bad, but because it requires both projects to be released at the same time. And that doesn't make sense considering [this blog post](http://www.continuousimprover.com/2016/10/principles-for-successful-package.html).

**Comment by vossad01** [comment]
I will admit I was surprised when I tracked it (FluentAssertions.Json) back to this repository.  When I first noticed the package I thought I should [add it to the website](http://www.fluentassertions.com/#community-extensions) and it took a few hops tracking it back here to see that wasn't so applicable.

I'm not thinking of anything that would inherently prevent independent artifacts out of a repository, even if not the cleanest solution.  I so assume it is mostly an implementation/configuration thing that they must be released at the same.

I was mainly writing to say was that if you ever do get to a point you want to split it out to its own repository, I have the requisite experience with Git if you wanted assistance.  Its not especially hard and I imagine it likely you probably are experienced with it as well, but I never quite know how deep people are into Git so figured I'd mention it.

**Comment by nohwnd** [comment]
Thanks for the tips. I think that the best place for my extensions would be a new package called FluentAssertions.WebApi, because MVC uses different stack, and JSON is often used without WebApi. I am writing a lot of those tests now, so I will first refine it internally, and release it later.

**Comment by kevinkuszyk** [comment]
@nohwnd apologies for taking some time to join this conversation.

If you're using MVC / WebApi Core (Microsoft merged the frameworks in MVC Core), we already have beta support in FluentAssertions.AspNetCore.Mvc.  If you want to add features I would welcome a PR!

If not, welcome to the FA community extensions club!

**Comment by nohwnd** [comment]
I am in fact using Core. I will have a look on what you are doing there, and contribute once I have something :)
